export const BASE_URL = 'https://us-central1-labenu-apis.cloudfunctions.net/labeX/joao-resende-lamarr/'

export const tripOptions = [
    { value: "Escolha uma viagem" },

];


export const countryOptions = [
    { value: "Escolha um país" },
    { value: "Afeganistão" },
    { value: "África do Sul" },
	{ value: "Albânia" },
    { value: "Alemanha" },
    { value: "Andorra" },
    { value: "Angola" },
    { value: "Anguilla" },
    { value: "Antilhas Holandesas" },
    { value: "Antárctida" },
    { value: "Argentina" },
    { value: "Argélia" },
    { value: "Armênia" },
    { value: "Aruba" },
    { value: "Arábia Saudita" },
    { value: "Austrália" },
    { value: "Áustria" },
    { value: "Azerbaijão" },
    { value: "Bahamas" },
    { value: "Bahrein" },
    { value: "Bangladesh" },
    { value: "Barbados" },
    { value: "Belize" },
    { value: "Benim" },
    { value: "Bermudas" },
    { value: "Bielorrússia" },
    { value: "Bolívia" },
    { value: "Botswana" },
    { value: "Brunei" },
    { value: "Bulgária" },
    { value: "Burkina Faso" },
    { value: "Burundi" },
    { value: "Butão" },
    { value: "Bélgica" },
    { value: "Bósnia e Herzegovina" },
    { value: "Brasil" },
    { value: "Cabo Verde" },
    { value: "Camarões" },
    { value: "Camboja" },
    { value: "Canadá" },
    { value: "Catar" },
    { value: "Cazaquistão" },
    { value: "Chade" },
    { value: "Chile" },
    { value: "China" },
    { value: "Chipre" },
    { value: "Colômbia" },
    { value: "Comores" },
    { value: "Coreia do Norte" },
    { value: "Coreia do Sul" },
    { value: "Costa do Marfim" },
    { value: "Costa Rica" },
    { value: "Croácia" },
    { value: "Cuba" },
    { value: "Dinamarca" },
    { value: "Djibouti" },
    { value: "Dominica" },
    { value: "Egito" },
    { value: "El Salvador" },
    { value: "Emirados Árabes Unidos" },
    { value: "Equador" },
    { value: "Eritreia" },
    { value: "Escócia" },
    { value: "Eslováquia" },
    { value: "Eslovênia" },
    { value: "Espanha" },
    { value: "Estados Federados da Micronésia" },
    { value: "Estados Unidos" },
    { value: "Estônia" },
    { value: "Etiópia" },
    { value: "Fiji" },
    { value: "Filipinas" },
    { value: "Finlândia" },
    { value: "França" },
    { value: "Gabão" },
    { value: "Gana" },
    { value: "Geórgia" },
    { value: "Gibraltar" },
    { value: "Granada" },
    { value: "Gronelândia" },
    { value: "Grécia" },
    { value: "Guadalupe" },
    { value: "Guam" },
    { value: "Guatemala" },
    { value: "Guernesei" },
    { value: "Guiana" },
    { value: "Guiana Francesa" },
    { value: "Guiné" },
    { value: "Guiné Equatorial" },
    { value: "Guiné-Bissau" },
    { value: "Gâmbia" },
    { value: "Haiti" },
    { value: "Honduras" },
    { value: "Hong Kong" },
    { value: "Hungria" },
    { value: "Ilha Bouvet" },
    { value: "Ilha de Man" },
    { value: "Ilha do Natal" },
    { value: "Ilha Heard e Ilhas McDonald" },
    { value: "Ilha Norfolk" },
    { value: "Ilhas Cayman" },
    { value: "Ilhas Cocos (Keeling)" },
    { value: "Ilhas Cook" },
    { value: "Ilhas Feroé" },
    { value: "Ilhas Geórgia do Sul e Sandwich do Sul" },
    { value: "Ilhas Malvinas" },
    { value: "Ilhas Marshall" },
    { value: "Ilhas Menores Distantes dos Estados Unidos" },
    { value: "Ilhas Salomão" },
    { value: "Ilhas Virgens Americanas" },
    { value: "Ilhas Virgens Britânicas" },
    { value: "Ilhas Åland" },
    { value: "Indonésia" },
    { value: "Inglaterra" },
    { value: "Índia" },
    { value: "Iraque" },
    { value: "Irlanda do Norte" },
    { value: "Irlanda" },
    { value: "Irã" },
    { value: "Islândia" },
    { value: "Israel" },
    { value: "Itália" },
    { value: "Iêmen" },
    { value: "Jamaica" },
    { value: "Japão" },
    { value: "Jersey" },
    { value: "Jordânia" },
    { value: "Kiribati" },
    { value: "Kuwait" },
    { value: "Laos" },
    { value: "Lesoto" },
    { value: "Letônia" },
    { value: "Libéria" },
    { value: "Liechtenstein" },
    { value: "Lituânia" },
    { value: "Luxemburgo" },
    { value: "Líbano" },
    { value: "Líbia" },
    { value: "Macau" },
    { value: "Macedônia" },
    { value: "Madagáscar" },
    { value: "Malawi" },
    { value: "Maldivas" },
    { value: "Mali" },
    { value: "Malta" },
    { value: "Malásia" },
    { value: "Marianas Setentrionais" },
    { value: "Marrocos" },
    { value: "Martinica" },
    { value: "Mauritânia" },
    { value: "Maurícia" },
    { value: "Mayotte" },
    { value: "Moldávia" },
    { value: "Mongólia" },
    { value: "Montenegro" },
    { value: "Moçambique" },
    { value: "Myanmar" },
    { value: "México" },
    { value: "Mônaco" },
    { value: "Namíbia" },
    { value: "Nauru" },
    { value: "Nepal" },
    { value: "Nicarágua" },
    { value: "Nigéria" },
    { value: "Niue" },
    { value: "Noruega" },
    { value: "Nova Caledônia" },
    { value: "Nova Zelândia" },
    { value: "Níger" },
    { value: "Omã" },
    { value: "Palau" },
    { value: "Palestina" },
    { value: "Panamá" },
    { value: "Papua-Nova Guiné" },
    { value: "Paquistão" },
    { value: "Paraguai" },
    { value: "País de Gales" },
    { value: "Países Baixos" },
    { value: "Peru" },
    { value: "Pitcairn" },
    { value: "Polinésia Francesa" },
    { value: "Polônia" },
    { value: "Porto Rico" },
    { value: "Portugal" },
    { value: "Quirguistão" },
    { value: "Quênia" },
    { value: "Reino Unido" },
    { value: "República Centro-Africana" },
    { value: "República Checa" },
    { value: "República Democrática do Congo" },
    { value: "República Dominicana" },
    { value: "Reunião" },
    { value: "Romênia" },
    { value: "Ruanda" },
    { value: "Rússia" },
    { value: "Saara Ocidental" },
    { value: "Saint Martin" },
    { value: "Saint-Barthélemy" },
    { value: "Saint-Pierre e Miquelon" },
    { value: "Samoa Americana" },
    { value: "Samoa" },
    { value: "Santa Helena, Ascensão e Tristão da Cunha" },
    { value: "Santa Lúcia" },
    { value: "Senegal" },
    { value: "Serra Leoa" },
    { value: "Seychelles" },
    { value: "Singapura" },
    { value: "Somália" },
    { value: "Sri Lanka" },
    { value: "Suazilândia" },
    { value: "Sudão" },
    { value: "Suriname" },
    { value: "Suécia" },
    { value: "Suíça" },
    { value: "Svalbard e Jan Mayen" },
    { value: "São Cristóvão e Nevis" },
    { value: "São Marino" },
    { value: "São Tomé e Príncipe" },
    { value: "São Vicente e Granadinas" },
    { value: "Sérvia" },
    { value: "Síria" },
    { value: "Tadjiquistão" },
    { value: "Tailândia" },
    { value: "Taiwan" },
    { value: "Tanzânia" },
    { value: "Terras Austrais e Antárticas Francesas" },
    { value: "Território Britânico do Oceano Índico" },
    { value: "Timor-Leste" },
    { value: "Togo" },
    { value: "Tonga" },
    { value: "Toquelau" },
    { value: "Trinidad e Tobago" },
    { value: "Tunísia" },
    { value: "Turcas e Caicos" },
    { value: "Turquemenistão" },
    { value: "Turquia" },
    { value: "Tuvalu" },
    { value: "Ucrânia" },
    { value: "Uganda" },
    { value: "Uruguai" },
    { value: "Uzbequistão" },
    { value: "Vanuatu" },
    { value: "Vaticano" },
    { value: "Venezuela" },
    { value: "Vietname" },
    { value: "Wallis e Futuna" },
    { value: "Zimbabwe" },
    { value: "Zâmbia" }
]
